#!/usr/bin/env python3
"""Phase D (intro/concl/abstract): assemble final_prose from the 3 ledgers into LaTeX body
fragments the uOttawa draft \\inputs. Source of truth = *_paragraph_ledger.json final_prose."""
import json
from pathlib import Path

REW = Path(r"C:\Users\sinas\OneDrive\Desktop\Projects\Thesis_Bmad\Data\Data\Datasets\Datasets\Data_Processing\F1D\docs\Thesis\rewrite")
THESIS = Path(r"C:\Users\sinas\OneDrive\Desktop\Projects\Thesis_Bmad\Data\Data\Datasets\Datasets\Data_Processing\F1D\docs\Thesis")
HEADER = "% AUTO-GENERATED by tmp/build_introconcl_body.py from {src} (final_prose). Do not hand-edit.\n"


def body(ledger_file):
    d = json.loads((REW / ledger_file).read_text(encoding="utf-8"))
    paras = sorted(d["paragraphs"], key=lambda p: p.get("order", 0))
    return "\n\n".join(p["final_prose"].strip() for p in paras if p.get("final_prose", "").strip())


units = [
    ("section_abstract_paragraph_ledger.json", "_abstract_body.tex"),
    ("section1_paragraph_ledger.json", "_intro_body.tex"),
    ("section5_paragraph_ledger.json", "_conclusion_body.tex"),
]
for src, out in units:
    txt = body(src)
    (THESIS / out).write_text(HEADER.format(src=src) + txt + "\n", encoding="utf-8")
    print(f"{out:22} <- {src}: {len(txt.split())} words, {txt.count(chr(10) + chr(10)) + 1} paragraphs")
