# Phase D: assemble Section 3 + 4 body prose from the Phase-C paragraph ledgers' final_prose
# into docs/Thesis/sec34_body_from_ledgers.tex (auto-generated; do not hand-edit).
# Chapter 3 = the four 3.x subsections; Chapter 4 = 4.1. Each subsection -> \section{title}; each
# paragraph's final_prose -> one LaTeX paragraph (blank line between).
import json, pathlib
ROOT = pathlib.Path(r"C:\Users\sinas\OneDrive\Desktop\Projects\Thesis_Bmad\Data\Data\Datasets\Datasets\Data_Processing\F1D")
DEST = ROOT / "docs/Thesis/rewrite"
OUT = ROOT / "docs/Thesis/sec34_body_from_ledgers.tex"

def section(sid):
    led = json.loads((DEST / f"section{sid}_paragraph_ledger.json").read_text(encoding="utf-8"))
    lines = [f"\\section{{{led['title'].split(': ', 1)[-1] if sid != '3.1' else led['title']}}}"]
    # keep full titles (incl. "Main Analysis 1: ...") -- they read well as section heads
    lines = [f"\\section{{{led['title']}}}", ""]
    for para in led["paragraphs"]:
        prose = para.get("final_prose", "").strip()
        assert prose, f"empty final_prose in {sid} {para['para_id']}"
        lines.append(prose)
        lines.append("")           # blank line = paragraph break
    return "\n".join(lines)

body = []
body.append("% AUTO-GENERATED by tmp/build_sec34_body.py from the Phase-C paragraph ledgers.")
body.append("% Source of truth = section{3.1,3.2,3.3,3.4,4.1}_paragraph_ledger.json final_prose. Do NOT hand-edit.")
body.append("")
body.append("\\chapter{Main Empirical Analyses}\\label{ch:main}")
body.append("")
for sid in ["3.1", "3.2", "3.3", "3.4"]:
    body.append(section(sid))
body.append("\\chapter{Additional Analyses}\\label{ch:additional}")
body.append("")
body.append(section("4.1"))

OUT.write_text("\n".join(body) + "\n", encoding="utf-8")
print("wrote", OUT.name, "-", OUT.stat().st_size, "bytes")
