"""Generate docs/Thesis/_tables_from_bible.tex — BYTE-EXACT table blocks pulled from
the bible (docs/Draft/thesis_tables.tex + its \\input fragment files). Never hand-edit
the output; rerun this script after any bible change.

Ordering = first \\ref occurrence in docs/Thesis/thesis_draft.tex.
The empire deal-specification page (_empire_building_spec.tex) is inserted immediately
before tab:empire_building_did so the draft's "page preceding Table X" sentence stays true.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DRAFT = ROOT / "docs" / "Thesis" / "thesis_draft.tex"
BIBLE_DIR = ROOT / "docs" / "Draft"
BIBLE = BIBLE_DIR / "thesis_tables.tex"
OUT = ROOT / "docs" / "Thesis" / "_tables_from_bible.tex"

# label -> fragment file (the \input constituents ARE the bible). Labels not listed
# here are extracted from thesis_tables.tex's own body.
FRAGMENT = {
    "tab:summary_stats": "_summary_stats.tex",
    "tab:empire_building_did": "_empire_building_did.tex",
    "tab:empire_drop_matched": "_empire_drop_matched.tex",
    "tab:empire_drop_placebo": "_empire_drop_placebo.tex",
    "tab:empire_cashspec": "_empire_cashspec.tex",
    "tab:cash_scrutiny_validity": "_cash_scrutiny_validity.tex",
    "tab:cash_scrutiny_channel": "_cash_scrutiny_channel.tex",
    "tab:reason_gating": "_reason_gating.tex",
}

draft = DRAFT.read_text(encoding="utf-8")
order, seen = [], set()
for m in re.finditer(r"\\ref\{(tab:[^}]+)\}", draft):
    lab = m.group(1)
    if lab not in seen:
        seen.add(lab)
        order.append(lab)

# Summary statistics is Table 1 by corporate-finance convention: placed FIRST in
# the tables section even though the text forward-references result tables earlier
# (the framework cites 10 tables before the Data section first cites summary stats).
# \ref resolves to the printed number, so all cross-references stay correct.
if "tab:summary_stats" in order:
    order.remove("tab:summary_stats")
    order.insert(0, "tab:summary_stats")

bible = BIBLE.read_text(encoding="utf-8")

def block_from_bible(label: str) -> str:
    """Byte-exact \\begin{table}...\\end{table} block containing \\label{label}."""
    i = bible.find("\\label{%s}" % label)
    if i < 0:
        sys.exit(f"ERROR: label {label} not found in thesis_tables.tex")
    start = bible.rfind("\\begin{table}", 0, i)
    end = bible.find("\\end{table}", i)
    if start < 0 or end < 0:
        sys.exit(f"ERROR: table environment for {label} not delimited")
    return bible[start : end + len("\\end{table}")]

parts = [
    "% AUTO-GENERATED by tmp/extract_draft_tables.py — BYTE-EXACT copies from the bible",
    "% (docs/Draft/thesis_tables.tex + fragments). DO NOT HAND-EDIT. Regenerate instead.",
    "",
]
for lab in order:
    if lab == "tab:empire_building_did":
        spec = (BIBLE_DIR / "_empire_building_spec.tex").read_text(encoding="utf-8")
        parts += ["% --- deal-specification page (precedes the run-up table, as cited in the text)",
                  spec.rstrip(), "\\clearpage", ""]
    if lab in FRAGMENT:
        body = (BIBLE_DIR / FRAGMENT[lab]).read_text(encoding="utf-8").rstrip()
    else:
        body = block_from_bible(lab)
    parts += [f"% --- {lab}", body, "\\clearpage", ""]

OUT.write_text("\n".join(parts), encoding="utf-8")
labs_out = re.findall(r"\\label\{(tab:[^}]+)\}", OUT.read_text(encoding="utf-8"))
print("draft cite order :", order)
print("labels in output :", labs_out)
missing = [l for l in order if l not in labs_out]
print("missing:", missing if missing else "NONE")
sys.exit(1 if missing else 0)
