"""Generate docs/Thesis/_tables_from_bible.tex — BYTE-EXACT table blocks pulled from
the bible (docs/Draft/thesis_tables.tex + its \\input fragment files). Never hand-edit
the output; rerun this script after any bible change.

Ordering = first \\ref occurrence in docs/Thesis/thesis_draft.tex.
The empire deal-specification page (_empire_building_spec.tex) is inserted immediately
before tab:empire_building_did so the draft's "page preceding Table X" sentence stays true.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DRAFT = ROOT / "docs" / "Thesis" / "thesis_draft.tex"
BIBLE_DIR = ROOT / "docs" / "Draft"
BIBLE = BIBLE_DIR / "thesis_tables.tex"
OUT = ROOT / "docs" / "Thesis" / "_tables_from_bible.tex"

# label -> fragment file (the \input constituents ARE the bible). Labels not listed
# here are extracted from thesis_tables.tex's own body.
FRAGMENT = {
    # 2026-06-14: Table 1 is the whole-thesis all-universe summary stats emitted by
    # docs/Draft/generate_summary_stats.py (replaces the hand-built _summary_stats.tex).
    "tab:summary_stats": "summary_stats.tex",
    "tab:empire_building_did": "_empire_building_did.tex",
    "tab:empire_drop_matched": "_empire_drop_matched.tex",
    "tab:empire_drop_placebo": "_empire_drop_placebo.tex",
    "tab:empire_cashspec": "_empire_cashspec.tex",
    "tab:cash_scrutiny_validity": "_cash_scrutiny_validity.tex",
    "tab:cash_scrutiny_channel": "_cash_scrutiny_channel.tex",
    "tab:reason_gating": "_reason_gating.tex",
}

# 2026-06-14: the thesis table set is LOCKED (user-ratified: 11 tables, empire thesis).
# Order is EXPLICIT here, not driven by a \ref scan of thesis_draft.tex -- §2 (the only
# written section) cites no result tables, and the set/order is fixed. summary_stats is
# Table 1 (corporate-finance convention). Re-running is always safe.
THESIS_TABLES = [
    "tab:summary_stats",
    "tab:empire_building_did",
    "tab:empire_drop_matched",
    "tab:empire_drop_placebo",
    "tab:empire_cashspec",
    "tab:h11_prisk_uncertainty",
    "tab:h24_us_epu",
    "tab:h24b_global_epu",
    "tab:cash_scrutiny_validity",
    "tab:cash_scrutiny_channel",
    "tab:reason_gating",
]
order = list(THESIS_TABLES)

bible = BIBLE.read_text(encoding="utf-8")

def block_from_bible(label: str) -> str:
    """Byte-exact \\begin{table}...\\end{table} block containing \\label{label}."""
    i = bible.find("\\label{%s}" % label)
    if i < 0:
        sys.exit(f"ERROR: label {label} not found in thesis_tables.tex")
    start = bible.rfind("\\begin{table}", 0, i)
    end = bible.find("\\end{table}", i)
    if start < 0 or end < 0:
        sys.exit(f"ERROR: table environment for {label} not delimited")
    return bible[start : end + len("\\end{table}")]

def shrink_wide_tabulars(s: str) -> str:
    """Wrap each \\begin{tabular}...\\end{tabular} in adjustbox max-width so wide tables
    (built for the bible's landscape geometry) shrink to fit the thesis text block; tables
    that already fit are unchanged. longtable (summary_stats) is a different env -> untouched.
    Content stays byte-exact; only a width wrapper is added."""
    # max width=\linewidth (NOT \textwidth): \linewidth tracks the current line width, so
    # landscape-wrapped tables fit the ROTATED width (full size) while portrait tables fit the
    # text block; \textwidth would wrongly shrink landscape tables to the portrait width.
    s = s.replace("\\begin{tabular}", "\\begin{adjustbox}{max width=\\linewidth}\n\\begin{tabular}")
    s = s.replace("\\end{tabular}", "\\end{tabular}\n\\end{adjustbox}")
    return s

parts = [
    "% AUTO-GENERATED by tmp/extract_draft_tables.py — table CONTENT byte-exact from the bible",
    "% (docs/Draft/thesis_tables.tex + fragments), each tabular adjustbox-wrapped to fit width.",
    "% DO NOT HAND-EDIT. Regenerate instead.",
    "",
]
# Widest tables -> landscape (full-size, rotated) instead of heavy portrait shrink (user 2026-06-14).
# The deal-spec page rides with the run-up table. pdflscape's landscape env issues its own
# \clearpage at both ends, so no extra \clearpage is added around landscaped blocks.
LANDSCAPE = {"tab:empire_building_did"}
for lab in order:
    if lab == "tab:empire_building_did":
        spec = (BIBLE_DIR / "_empire_building_spec.tex").read_text(encoding="utf-8")
        parts += ["% --- deal-specification page (landscape; precedes the run-up table)",
                  "\\begin{landscape}", shrink_wide_tabulars(spec.rstrip()), "\\end{landscape}", ""]
    if lab in FRAGMENT:
        body = (BIBLE_DIR / FRAGMENT[lab]).read_text(encoding="utf-8").rstrip()
    else:
        body = block_from_bible(lab)
    body = shrink_wide_tabulars(body)
    if lab in LANDSCAPE:
        parts += [f"% --- {lab} (landscape)", "\\begin{landscape}", body, "\\end{landscape}", ""]
    else:
        parts += [f"% --- {lab}", body, "\\clearpage", ""]

OUT.write_text("\n".join(parts), encoding="utf-8")
labs_out = re.findall(r"\\label\{(tab:[^}]+)\}", OUT.read_text(encoding="utf-8"))
print("draft cite order :", order)
print("labels in output :", labs_out)
missing = [l for l in order if l not in labs_out]
print("missing:", missing if missing else "NONE")
sys.exit(1 if missing else 0)
