# -*- coding: utf-8 -*-
"""Emit the COMPLETE schema of the 16 _final/ ledgers as an organized tree -> one .txt.
Reads every file (no hand-typing), so the doc is always faithful + re-runnable.
  python gen_schema_tree.py        ->  _final/_SCHEMA_TREE.txt

Output has 3 parts:
  1. INVENTORY      16 files -> Format A/B, #paragraphs, #props
  2. ABSTRACT SCHEMA  shared trunk + Format A tree + Format B tree (types + X/N presence)
  3. PER-FILE SKELETON  every file -> its paragraphs -> its prop_ids (+ type + statement stub)
"""
import json
from pathlib import Path

RW = Path(__file__).resolve().parent
FIN = RW / "_final"
OUT = FIN / "_SCHEMA_TREE.txt"
ORD = {s: i for i, s in enumerate(
    ["_abstract", "1", "2.1", "2.2", "2.3", "2.4", "2.5",
     "3.1", "3.2", "3.3", "3.4", "4.1", "4.2", "4.3", "4.4", "5"])}

def vtype(v):
    if v is None: return "null"
    if isinstance(v, bool): return "bool"
    if isinstance(v, dict): return "obj"
    if isinstance(v, list):
        return "[]" if not v else ("[obj]" if isinstance(v[0], dict) else f"[{vtype(v[0])}]")
    if isinstance(v, str): return "str"
    if isinstance(v, (int, float)): return "num"
    return type(v).__name__

def forest(children, prefix=""):
    """children = list of (label, subchildren). Returns ascii-tree lines."""
    out = []
    for i, (label, sub) in enumerate(children):
        last = i == len(children) - 1
        out.append(prefix + ("└─ " if last else "├─ ") + label)
        out += forest(sub, prefix + ("   " if last else "│  "))
    return out

# ---- load + partition ----
files = sorted(FIN.glob("section*_paragraph_ledger.json"),
               key=lambda f: ORD.get(json.loads(f.read_text(encoding="utf-8"))["section_id"], 99))
recs = [(f, json.loads(f.read_text(encoding="utf-8"))) for f in files]
A = [(f, d) for f, d in recs if isinstance(d["paragraphs"], dict)]
B = [(f, d) for f, d in recs if isinstance(d["paragraphs"], list)]

def paras_of(d):
    p = d["paragraphs"]
    return list(p.items()) if isinstance(p, dict) else [(x.get("para_id", f"#{i}"), x) for i, x in enumerate(p)]
def props_of(p):
    return p.get("propositions") or p.get("proposition_chain") or []

def agg(fam):
    pf, prf = {}, {}
    npar = npr = 0
    plk = None; sctx = []
    for _, d in fam:
        sc = d.get("section_context", {})
        if isinstance(sc, dict):
            for k in sc:
                if k not in sctx: sctx.append(k)
        for _, p in paras_of(d):
            if not isinstance(p, dict): continue
            npar += 1
            for k, v in p.items():
                if k in ("propositions", "proposition_chain"): plk = k; continue
                e = pf.setdefault(k, [0, vtype(v)]); e[0] += 1
            for pr in props_of(p):
                if not isinstance(pr, dict): continue
                npr += 1
                for k, v in pr.items():
                    e = prf.setdefault(k, [0, vtype(v)]); e[0] += 1
    return dict(pf=pf, prf=prf, npar=npar, npr=npr, plk=plk, sctx=sctx, n=len(fam))

ga, gb = agg(A), agg(B)

GUARDS = {"source", "anchor_2_1", "evidence", "numbers", "register_locks"}
def fields_nodes(fd, total):
    out = []
    for k, (c, ty) in sorted(fd.items(), key=lambda x: (-x[1][0], x[0])):
        tag = ""
        if k == "final_prose":   tag = "   <== WRITE HERE (empty)"
        elif k == "statement":   tag = "   = the CLAIM to render"
        elif k in GUARDS:        tag = "   ★ honesty/overclaim guard"
        out.append((f"{k:18} : {ty:6}  ({c}/{total}){tag}", []))
    return out

def fmt_tree(title, container, g):
    pc = fields_nodes(g["pf"], g["npar"])
    pc.append((f'{g["plk"]:18} : [obj]   <-- PROP LIST', fields_nodes(g["prf"], g["npr"])))
    return [title, "│"] + forest([(f"paragraphs : {container}", pc)])

L = []
def w(*xs): L.extend(xs)

w("="*72)
w("  _final/ LEDGER SCHEMA  -  the 16 prose-ready files (derived from corpus_audited)")
w("  generated by gen_schema_tree.py  (re-run after any structural change)")
w("="*72, "")
w("LEGEND:  name : type (X/N)  -> field present in X of N items at that level.")
w("         final_prose = \"\"  is the ONLY empty field -> the prose-writing target.")
w("         ★ = overclaim/honesty guard you must READ before writing that prop.", "")

# PART 1
w("#"*72, "#  PART 1 - INVENTORY  (16 files -> format)", "#"*72, "")
w(f"  {'section':10} {'format':8} {'paras':6} {'props':6}")
w(f"  {'-'*10} {'-'*8} {'-'*6} {'-'*6}")
for f, d in recs:
    fmt = "A" if isinstance(d["paragraphs"], dict) else "B"
    npar = sum(1 for _, p in paras_of(d) if isinstance(p, dict))
    npr = sum(len(props_of(p)) for _, p in paras_of(d) if isinstance(p, dict))
    w(f"  {d['section_id']:10} {fmt:8} {npar:<6} {npr:<6}")
w("", f"  FORMAT A = {ga['n']} files, {ga['npar']} paras, {ga['npr']} props   (theory/hypotheses)")
w(f"  FORMAT B = {gb['n']} files, {gb['npar']} paras, {gb['npr']} props   (abstract/intro/data/results/concl)", "")

# PART 2
w("#"*72, "#  PART 2 - ABSTRACT SCHEMA  (shared trunk, then the two formats)", "#"*72, "")
w("SHARED TRUNK  (identical in all 16 files):")
w(*forest([
    ("_derived_from   : str        lineage", []),
    ("_bright_lines   : [str]      GLOBAL honesty rules", []),
    ("section_id      : str", []),
    ("title           : str", []),
    ("guards_added    : [str]      section-level guards", []),
    ("section_context : obj        A:{%s}  B:{%s}" % (", ".join(ga["sctx"]), ", ".join(gb["sctx"])), []),
    ("paragraphs      : <<FORK>>   A = obj{P1..}   B = list[..]", []),
]))
w("")
w(*fmt_tree("FORMAT A  (§2.1-2.5)", "obj { P1, P2, ... }  (DICT, keyed)", ga))
w("")
w(*fmt_tree("FORMAT B  (abstract, §1, §3, §4, §5)", "list [ {..}, {..} ]  (LIST)", gb))
w("")

# PART 3
w("#"*72, "#  PART 3 - PER-FILE SKELETON  (every file -> paragraphs -> prop_ids)", "#"*72, "")
for f, d in recs:
    fmt = "A" if isinstance(d["paragraphs"], dict) else "B"
    items = paras_of(d)
    npr = sum(len(props_of(p)) for _, p in items if isinstance(p, dict))
    kids = []
    for pid, p in items:
        if not isinstance(p, dict): continue
        pk = []
        for pr in props_of(p):
            if not isinstance(pr, dict): continue
            stmt = " ".join((pr.get("statement") or "").split())[:58]
            pk.append((f"{pr.get('prop_id','?'):12} [{pr.get('type','?')}]  {stmt}…", []))
        kids.append((str(pid), pk))
    w(f"section{d['section_id']}  [{fmt}]  ({len([1 for _,p in items if isinstance(p,dict)])} ¶ · {npr} props)")
    w(*forest(kids))
    w("")

OUT.write_text("\n".join(L), encoding="utf-8")
print(f"WROTE {OUT}")
print(f"  lines={len(L)}  size={OUT.stat().st_size:,}B")
print(f"  Format A: {ga['n']} files / {ga['npar']} paras / {ga['npr']} props")
print(f"  Format B: {gb['n']} files / {gb['npar']} paras / {gb['npr']} props")
