"""GEN — emit the Campello Table-8 rebuild LaTeX fragment from step JSON.

Single source of truth = a step summary.json with a `results` list (each
entry carrying a full `coefficients` table) plus a `campello_reference`.
NO numbers are hardcoded here: every coefficient, SE, N, R², and the
Campello reference column are read from JSON; significance stars are
computed from the stored t/p. Results-driven: one data column per entry
in `results`, plus the Campello reference column.

Default source = latest step7_fullpanel_hypothesis (the CANONICAL
full-sample-period eq-(14): panel 2010Q1–2016Q4, POST dummy=1 only
2016Q3–Q4 — NOT the superseded 4-qtr Step-6 framing). Override with a
positional arg naming a step subdir under outputs/campello_rebuild/.

Writes docs/Draft/_campello_rebuild_t8.tex, \\input by thesis_tables.tex.
Run: python scripts/campello_rebuild/gen_thesis_t8_table.py [step_subdir]
"""
from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "Draft" / "_campello_rebuild_t8.tex"
DEFAULT_STEP = "step7_fullpanel_hypothesis"

LABEL = {
    "POST_x_HIGH": r"POST $\times$ HIGH $U^{UK}$ ($\hat{\delta}$)",
    "brexit_stock_return": r"brexit\_stock\_return",
    "brexit_tobins_q": r"brexit\_tobins\_q",
    "brexit_cash_flow": r"brexit\_cash\_flow",
    "brexit_sales_growth": r"brexit\_sales\_growth",
    "log_assets": r"log\_assets",
    "log_assets_l1": r"log\_assets",
    "cons_fwd": r"Consensus EPS",
    "cons_lag1": r"Consensus EPS",
}
FIRM_ORDER = ["brexit_stock_return", "brexit_tobins_q", "brexit_cash_flow",
              "brexit_sales_growth"]  # log_assets + consensus appended below
# tag -> (line1, line2) column header
HEAD = {
    "FULL_PANEL": ("Rebuild", "full panel"),
    "A_forward": ("Rebuild A", "consensus fwd"),
    "B_lag1": ("Rebuild B", "consensus 1Q-lag"),
}


def _latest(sub: str) -> tuple[dict, str, str]:
    base = ROOT / "outputs" / "campello_rebuild" / sub
    d = sorted(p for p in base.iterdir() if p.is_dir())[-1]
    return (json.loads((d / "summary.json").read_text(encoding="utf-8")),
            sub, d.name)


def _stars2(p: float) -> str:
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.10 else ""


def _stars1_pos(coef: float, p_two: float) -> str:
    """Campello's hypothesis is delta > 0: one-tailed in the + direction."""
    return _stars2(p_two / 2 if coef > 0 else 1 - p_two / 2)


def _cell(coef: float, star: str) -> str:
    body = f"{coef:.4f}{('$^{' + star + '}$') if star else ''}"
    return rf"\textbf{{{body}}}" if star else body


def main() -> None:
    sub = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_STEP
    s, sub, src = _latest(sub)
    results = s["results"]
    ref = s["campello_reference"]
    ncol = len(results) + 1                       # rebuild cols + Campello

    # per-result name->coef map and consensus column name
    cmap = [{c["name"]: c for c in r["coefficients"]} for r in results]
    cons = [r.get("consensus_variant", "cons_fwd") for r in results]
    row_order = ["POST_x_HIGH"] + FIRM_ORDER + ["__LOGA__", "__CONS__"]

    L: list[str] = []
    ap = L.append
    ap(r"% AUTO-GENERATED by scripts/campello_rebuild/gen_thesis_t8_table.py")
    ap(rf"% source: outputs/campello_rebuild/{sub}/{src}/summary.json")
    ap(rf"% generated: {datetime.now().isoformat(timespec='seconds')} "
       r"— DO NOT EDIT BY HAND")
    ap(r"\begin{table}[htbp]")
    ap(r"\centering")
    ap(r"\caption{Brexit Referendum Difference-in-Differences: Cash Holdings "
       r"--- Supervised From-Scratch Rebuild of Campello et al. (2022 JFQA) "
       r"Table 8, equation (14)}")
    ap(r"\label{tab:h1_5_brexit_did}")
    ap(r"\scriptsize")
    ap(r"\begin{tabular}{l" + "c" * ncol + "}")
    ap(r"\toprule")
    ap(" & " + " & ".join(f"({i+1})" for i in range(ncol)) + r" \\")
    h1 = [HEAD.get(r["tag"], (r["tag"], ""))[0] for r in results] + \
         ["Campello (2022)"]
    h2 = [HEAD.get(r["tag"], (r["tag"], ""))[1] for r in results] + \
         ["Table 8, col.~1"]
    ap(" & " + " & ".join(h1) + r" \\")
    ap(" & " + " & ".join(h2) + r" \\")
    ap(r"\midrule")

    for key in row_order:
        if key == "POST_x_HIGH":
            cells = [_cell(m["POST_x_HIGH"]["coef"],
                           _stars1_pos(m["POST_x_HIGH"]["coef"],
                                       m["POST_x_HIGH"]["pvalue"]))
                     for m in cmap]
            cells.append(_cell(ref["cash_delta"], ref.get("stars", "")))
            ses = [f"({m['POST_x_HIGH']['se']:.4f})" for m in cmap] + \
                  [f"({ref['se']:.4f})"]
            ap(f"{LABEL['POST_x_HIGH']} & " + " & ".join(cells) + r" \\")
            ap(" & " + " & ".join(ses) + r" \\")
            ap(r"\midrule")
            continue
        if key == "__LOGA__":
            getn = lambda m: m.get("log_assets") or m.get("log_assets_l1")
            lbl = LABEL["log_assets"]
            ents = [getn(m) for m in cmap]
        elif key == "__CONS__":
            ents = [cmap[i][cons[i]] for i in range(len(results))]
            lbl = LABEL["cons_fwd"]
        else:
            ents = [m[key] for m in cmap]
            lbl = LABEL[key]
        vals = [_cell(e["coef"], _stars2(e["pvalue"])) for e in ents] + ["n.r."]
        ses = [f"({e['se']:.4f})" for e in ents] + [" "]
        ap(f"{lbl} & " + " & ".join(vals) + r" \\")
        ap(" & " + " & ".join(ses) + r" \\")
    ap(r"\midrule")
    yes = " & ".join(["Yes"] * ncol)
    ap(rf"Firm FE & {yes} \\")
    ap(rf"Industry (FIC100) $\times$ qtr FE & {yes} \\")
    ap(r"Macro controls & " + " & ".join(["Absorbed"] * ncol) + r" \\")
    ap(r"\midrule")
    ap(r"N & " + " & ".join([f"{r['nobs']:,}" for r in results]
                            + [f"{ref['n']:,}"]) + r" \\")
    ap(r"Firms & " + " & ".join([f"{r['n_firms']:,}" for r in results]
                                + ["n.r."]) + r" \\")
    ap(r"$R^2$ (within) & " + " & ".join(
        [f"{r['rsquared_within']:.4f}" for r in results]
        + [f"{ref['rsquared']:.2f}$^{{\\dagger}}$"]) + r" \\")
    ap(r"\bottomrule")
    ap(r"\end{tabular}")
    ap(r"\begin{minipage}{\linewidth}")
    ap(r"\vspace{2pt}\scriptsize")
    ap(r"\textit{Notes:} $^{*}p<0.10$, $^{**}p<0.05$, $^{***}p<0.01$ "
       r"(one-tailed for the $\hat{\delta}$ interaction under Campello's "
       r"$\delta>0$ hypothesis; two-tailed for controls). Significant "
       r"coefficients in \textbf{bold}. n.r.~$=$ not reported by Campello "
       r"(Table 8 reports only the interaction).")
    ap(r" Standard errors (in parentheses) double-clustered at the firm and "
       r"calendar-quarter levels (verbatim Table 8 caption).")
    ap(r" Conditional eq.~(14): $\mathrm{CASH}_{i,t}=\alpha+\delta[\mathrm{"
       r"POST}_t\cdot\mathrm{HIGH}^{UK}_i]+\theta\cdot\mathrm{CONTROLS}_{i,"
       r"t-1}+\sum\mathrm{FIRM}_i+\sum\mathrm{INDUSTRY}(\mathrm{FIC100})_j"
       r"\times\mathrm{QUARTER}_t+\varepsilon$. CASH $=cheq_t/(atq_{t-1}-"
       r"cheq_{t-1})$ (Table 8 caption). Firm controls lagged one calendar "
       r"quarter. \textbf{Panel} $=$ the full sample period 2010:Q1--2016:Q4 "
       r"(unbalanced) for the $\beta^{UK}$-tercile treated and control "
       r"firms; $\mathrm{POST}=1$ only in 2016:Q3--Q4 --- the DiD "
       r"identifying contrast, \emph{not} a 4-quarter panel restriction "
       r"(established by $N$ arithmetic, $N$-match, and Campello's Table 12 "
       r"alternative-window specification). Consensus EPS uses the "
       r"native/forward key (forecast \emph{for} $t$ known at $t-1$); the "
       r"1Q-lag alternative was tested in the conditional step and is "
       r"immaterial ($\hat{\delta}$ differs by $<0.001$). Macro controls "
       r"carry no free coefficient: Campello's Industry$\times$time FE spans "
       r"all time-only variation, so any macro series is mechanically "
       r"absorbed under the paper's own specification (all columns).")
    ap(rf" Column ({ncol}) reproduces the verbatim Campello reference: "
       rf"{ref['source']}. $^{{\dagger}}$Campello's $R^2$ includes absorbed "
       r"fixed effects; rebuild columns report within-$R^2$ (not directly "
       r"comparable). The Campello figures are a reference benchmark, "
       r"\emph{not} an estimation or tuning target; this table reports the "
       r"rebuild's measured output only and asserts no replication verdict.")
    ap(r"\end{minipage}")
    ap(r"\end{table}")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"source : {sub}/{src}/summary.json  ({len(results)} rebuild col)")
    print(f"written: {OUT}")
    for r in results:
        print(f"  [{r['tag']}] δ̂ {r['delta_hat']:+.4f} ({r['se']:.4f})  "
              f"N {r['nobs']:,}  firms {r['n_firms']:,}")
    print(f"  Campello {ref['cash_delta']:+.3f}{ref.get('stars','')} "
          f"N {ref['n']:,}")


if __name__ == "__main__":
    main()
