"""Generate the summary-stats comparison LaTeX table for thesis_tables.pdf.

Reads:
  - tmp/campello_summary_stats_v2.json (machine-generated by _diag_summary_stats_v2.py)
  - tmp/campello_table1_panel_a.json (PyMuPDF extraction from paper PDF)
  - outputs/econometric/h1_5_brexit_did (treatment firm counts)
  - outputs/econometric/h1_5_brexit_did_psm (PSM matched firm counts)

Emits docs/Draft/_campello_summary_stats.tex — single panel, two column sets
(Rebuild vs Campello Table 1 Panel A). No numbers hand-typed.
No string matching — exact JSON keys + explicit mapping dict.

Run: python scripts/campello_rebuild/gen_summary_stats_tex.py
"""
from __future__ import annotations

import datetime as _dt
import json
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = Path(__file__).resolve().parents[2]
SRC_REBUILD = ROOT / "tmp" / "campello_summary_stats_v2.json"
SRC_CAMPELLO = ROOT / "tmp" / "campello_table1_panel_a.json"
SRC_DID = ROOT / "outputs" / "econometric" / "h1_5_brexit_did"
SRC_PSM = ROOT / "outputs" / "econometric" / "h1_5_brexit_did_psm"
SRC_C2 = (ROOT / "outputs" / "campello_rebuild" / "campello_c2"
          / "campello_c2_matched.json")
OUT = ROOT / "docs" / "Draft" / "_campello_summary_stats.tex"

# Our JSON key -> Campello PDF label (explicit, no inference)
OUR_KEY_TO_CAMPELLO_LABEL = {
    "CASH_T1": "CASH",
    "SIZE": "SIZE (Log Assets)",
    "STOCK_RETURNS": "STOCK_RETURNS",
    "TOBIN_Q": "TOBIN_Q",
    "CASH_FLOW": "CASH_FLOW",
    "SALES_GROWTH": "SALES_GROWTH",
    "CONSENSUS_EPS": "CONSENSUS_EARNINGS_FORECAST",
}

# Display order + LaTeX labels
VAR_LABELS = [
    ("CASH_T1", r"CASH\_T1"),
    ("SIZE", r"SIZE"),
    ("STOCK_RETURNS", r"STOCK\_RETURNS"),
    ("TOBIN_Q", r"TOBIN\_Q"),
    ("CASH_FLOW", r"CASH\_FLOW"),
    ("SALES_GROWTH", r"SALES\_GROWTH"),
    ("CONSENSUS_EPS", r"CONSENSUS\_EPS"),
]


def _num(v: float, dec: int = 3) -> str:
    return f"{v:+.{dec}f}"


def _num_n(v: int) -> str:
    return f"{v:,}"


def main() -> None:
    rebuild = json.loads(SRC_REBUILD.read_text(encoding="utf-8"))
    campello_raw = json.loads(SRC_CAMPELLO.read_text(encoding="utf-8"))
    campello = campello_raw["variables"]  # keyed by PDF label

    # Firm counts from DiD runner (market arm — beta^UK-tercile)
    did_dir = sorted(p for p in SRC_DID.iterdir() if p.is_dir())[-1]
    did = json.loads((did_dir / "summary.json").read_text(encoding="utf-8"))
    tc_mkt = did["treatment_counts"]["market"]
    tc_txt = did["treatment_counts"]["textual"]
    our_t, our_c = tc_mkt["rebuild"]["treated"], tc_mkt["rebuild"]["control"]
    camp_t, camp_c = tc_mkt["campello"]["treated"], tc_mkt["campello"]["control"]
    our_tt, our_ct = tc_txt["rebuild"]["treated"], tc_txt["rebuild"]["control"]
    camp_tt, camp_ct = tc_txt["campello"]["treated"], tc_txt["campello"]["control"]

    # PSM matched firm counts (treated / weighted-control unique firms)
    psm_dir = sorted(p for p in SRC_PSM.iterdir() if p.is_dir())[-1]
    psm = json.loads((psm_dir / "summary.json").read_text(encoding="utf-8"))
    p_mkt, p_txt = psm["results"][0], psm["results"][1]
    pm_t, pm_c = p_mkt["nT_firms"], p_mkt["nC_firms"]
    pt_t, pt_c = p_txt["nT_firms"], p_txt["nC_firms"]

    # Matched-sample CASH in T1 (cheq/atq_{t-1}) — comparable to Campello C.2.
    def _cash_t1(res: dict) -> dict:
        d = {x["variable"]: x for x in res["matched_summary"]}["CASH_T1"]
        return {"t": d["ours_treated"], "c": d["ours_control"]}
    our_cash = {"market": _cash_t1(p_mkt), "textual": _cash_t1(p_txt)}
    c2 = json.loads(SRC_C2.read_text(encoding="utf-8"))
    camp_cash = {arm: {"t": c2[arm]["CASH"]["treated"],
                       "c": c2[arm]["CASH"]["control"]}
                 for arm in ("market", "textual")}

    prov = (f"rebuild={SRC_REBUILD.name} ({rebuild['window']}), "
            f"campello={SRC_CAMPELLO.name}, psm={SRC_PSM.name}/{psm_dir.name}")
    gen = _dt.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

    body: list[str] = []
    for our_key, tex_label in VAR_LABELS:
        r = rebuild["variables"].get(our_key)
        if not r:
            continue
        campello_label = OUR_KEY_TO_CAMPELLO_LABEL[our_key]
        c = campello.get(campello_label, {})
        cells = [
            tex_label,
            _num(r["mean"]), _num(r["SD"]), _num(r["med"]),
            _num(r["IQR"]), _num_n(r["N"]),
            _num(c["mean"]), _num(c["SD"]), _num(c["med"]),
            _num(c["IQR"]), _num_n(c["N"]),
        ]
        body.append(" & ".join(cells) + r" \\")

    tex = [
        f"% AUTO-GENERATED by scripts/campello_rebuild/gen_summary_stats_tex.py",
        f"% sources: {prov}",
        f"% generated: {gen} --- DO NOT EDIT BY HAND",
        r"\begin{table}[p]",
        r"\centering",
        r"\caption{Campello Replication: Summary Statistics}",
        r"\label{tab:campello_summary_stats}",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{l rrrrr rrrrr}",
        r"\toprule",
        r" & \multicolumn{5}{c}{Rebuild} & "
        r"\multicolumn{5}{c}{Campello (2022) Table~1 Panel~A} \\",
        r"\cmidrule(lr){2-6}\cmidrule(lr){7-11}",
        r"Variable & mean & SD & med & IQR & N & "
        r"mean & SD & med & IQR & N \\",
        r"\midrule",
        *body,
        r"\midrule",
        rf"Firms --- market ($\beta^{{UK}}$-tercile, treated)"
        rf" & --- & --- & --- & --- & {our_t:,}"
        rf" & --- & --- & --- & --- & {camp_t:,} \\",
        rf"Firms --- market ($\beta^{{UK}}$-tercile, control)"
        rf" & --- & --- & --- & --- & {our_c:,}"
        rf" & --- & --- & --- & --- & {camp_c:,} \\",
        rf"Firms --- textual (\S1+7, $>$5 entries, treated)"
        rf" & --- & --- & --- & --- & {our_tt:,}"
        rf" & --- & --- & --- & --- & {camp_tt:,} \\",
        rf"Firms --- textual (\S1+7, zero entries, control)"
        rf" & --- & --- & --- & --- & {our_ct:,}"
        rf" & --- & --- & --- & --- & {camp_ct:,} \\",
        r"\addlinespace[2pt]",
        r"\multicolumn{11}{l}{\textit{PSM matched sample --- CASH "
        r"($cheq_t/atq_{t-1}$, T1) mean and firm count (N)}} \\",
        rf"\quad market PSM matched (treated)"
        rf" & {_num(our_cash['market']['t'])} & --- & --- & --- & {pm_t:,}"
        rf" & {_num(camp_cash['market']['t'])} & --- & --- & --- & n.r. \\",
        rf"\quad market PSM matched (control)"
        rf" & {_num(our_cash['market']['c'])} & --- & --- & --- & {pm_c:,}"
        rf" & {_num(camp_cash['market']['c'])} & --- & --- & --- & n.r. \\",
        rf"\quad textual PSM matched (treated)"
        rf" & {_num(our_cash['textual']['t'])} & --- & --- & --- & {pt_t:,}"
        rf" & {_num(camp_cash['textual']['t'])} & --- & --- & --- & n.r. \\",
        rf"\quad textual PSM matched (control)"
        rf" & {_num(our_cash['textual']['c'])} & --- & --- & --- & {pt_c:,}"
        rf" & {_num(camp_cash['textual']['c'])} & --- & --- & --- & n.r. \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    OUT.write_text("\n".join(tex), encoding="utf-8")
    print(f"written -> {OUT}")
    print(f"  {len(body)} variables")
    print(f"  PSM matched firms: market {pm_t}/{pm_c}, textual {pt_t}/{pt_c}")
    print(f"  matched CASH(T1) market: ours "
          f"{our_cash['market']['t']:.3f}/{our_cash['market']['c']:.3f} vs "
          f"camp {camp_cash['market']['t']:.3f}/{camp_cash['market']['c']:.3f}")
    print(f"  matched CASH(T1) textual: ours "
          f"{our_cash['textual']['t']:.3f}/{our_cash['textual']['c']:.3f} vs "
          f"camp {camp_cash['textual']['t']:.3f}/{camp_cash['textual']['c']:.3f}")


if __name__ == "__main__":
    main()
