"""GEN — side-by-side Campello Table-8 rebuild LaTeX fragment (8-col).

Single source of truth = step summary.json files. NO numbers hardcoded.

Columns (Sina 2026-05-31; CASH eq.14 + CASH PSM-matched + UncResCEO + Campello):
  (1) Rebuild CASH       βᵁᴷ-tercile   <- econometric/h1_5_brexit_did
  (2) Rebuild CASH       textual §1+7  <- econometric/h1_5_brexit_did
  (3) Rebuild CASH PSM   βᵁᴷ-tercile   <- econometric/h1_5_brexit_did_psm
  (4) Rebuild CASH PSM   textual §1+7  <- econometric/h1_5_brexit_did_psm
  (5) Rebuild UncResCEO  βᵁᴷ-tercile   <- econometric/h1_5_brexit_did_uncres
  (6) Rebuild UncResCEO  textual §1+7  <- econometric/h1_5_brexit_did_uncres
  (7) Campello T8 col.1  βᵁᴷ  CASH benchmark
  (8) Campello T8 col.2  textual CASH benchmark
Cols (1)--(6) share the SAME canonical eq-(14); cols (3)--(4) re-estimate it on
the PSM-matched, frequency-weighted sub-panel (3-NN with replacement on the 6
controls; OUR extension — Campello's PSM/Table C.3 is on investment/employment/
R&D/divestitures, not cash). Campello benchmarks CASH only (cols 7-8).

Writes docs/Draft/_campello_rebuild_t8.tex (\\input by thesis_tables.tex).
"""
from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "Draft" / "_campello_rebuild_t8.tex"
BREXIT_SUITE = "h1_5_brexit_did"          # CASH DV (both arms)
PSM_SUITE = "h1_5_brexit_did_psm"         # CASH DV, PSM-matched (both arms)
UNC_SUITE = "h1_5_brexit_did_uncres"      # UncResCEO DV (both arms)

LABEL = {
    "POST_x_HIGH": r"POST\_x\_HIGH",
    "brexit_stock_return": r"brexit\_stock\_return",
    "brexit_tobins_q": r"brexit\_tobins\_q",
    "brexit_cash_flow": r"brexit\_cash\_flow",
    "brexit_sales_growth": r"brexit\_sales\_growth",
    "log_assets": r"log\_assets",
    "cons_fwd": r"cons\_fwd",
}
FIRM_ORDER = ["brexit_stock_return", "brexit_tobins_q",
              "brexit_cash_flow", "brexit_sales_growth"]
# the 6 rebuild data columns (everything except the 2 Campello benchmark cols)
KEYS6 = ["cb", "c7", "pb", "p7", "ub", "u7"]


def _latest_econ(sub: str) -> tuple[dict, str]:
    base = ROOT / "outputs" / "econometric" / sub
    d = sorted(p for p in base.iterdir() if p.is_dir())[-1]
    return json.loads((d / "summary.json").read_text(encoding="utf-8")), d.name


def _stars2(p: float) -> str:
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.10 else ""


def _stars1_pos(coef: float, p_two: float) -> str:
    return _stars2(p_two / 2 if coef > 0 else 1 - p_two / 2)


def _cell(coef: float, star: str) -> str:
    body = f"{coef:.4f}{('$^{' + star + '}$') if star else ''}"
    return rf"\textbf{{{body}}}" if star else body


def _r2(x: float) -> str:
    return "0.0000" if abs(x) < 5e-5 else f"{x:.4f}"


def main() -> None:
    s_bx, d_bx = _latest_econ(BREXIT_SUITE)
    s_psm, d_psm = _latest_econ(PSM_SUITE)
    s_unc, d_unc = _latest_econ(UNC_SUITE)
    r_cb, r_c7 = s_bx["results"][0], s_bx["results"][1]   # CASH unmatched
    r_pb, r_p7 = s_psm["results"][0], s_psm["results"][1]  # CASH PSM
    r_ub, r_u7 = s_unc["results"][0], s_unc["results"][1]  # UncResCEO
    ref_b = s_bx["campello_reference_buk"]
    ref_t = s_bx["campello_reference_textual"]
    cnt_b = s_bx["treatment_counts"]["market"]["rebuild"]
    camp_b = s_bx["treatment_counts"]["market"]["campello"]
    camp_t = s_bx["treatment_counts"]["textual"]["campello"]
    s_t3b = s_bx["treatment_counts"]["textual"]["rebuild"]

    R = {"cb": r_cb, "c7": r_c7, "pb": r_pb, "p7": r_p7, "ub": r_ub, "u7": r_u7}
    M = {k: {c["name"]: c for c in R[k]["coefficients"]} for k in KEYS6}
    cons = {k: R[k].get("consensus_variant", "cons_fwd") for k in KEYS6}
    # one-tailed for CASH cols (cb,c7,pb,p7); two-tailed for UncResCEO (ub,u7)
    ONE_TAIL = {"cb", "c7", "pb", "p7"}
    cdef = s_bx.get("dv_tex", r"$cheq_t/(atq_{t-1} - cheq_{t-1})$")

    def delta_cell(k: str) -> str:
        c = M[k]["POST_x_HIGH"]
        st = (_stars1_pos(c["coef"], c["pvalue"]) if k in ONE_TAIL
              else _stars2(c["pvalue"]))
        return _cell(c["coef"], st)

    L: list[str] = []
    ap = L.append
    ap(r"% AUTO-GENERATED by scripts/campello_rebuild/gen_thesis_t8_table.py")
    ap(rf"% sources: econometric/{BREXIT_SUITE}/{d_bx} + "
       rf"{PSM_SUITE}/{d_psm} + {UNC_SUITE}/{d_unc}")
    ap(rf"% generated: {datetime.now().isoformat(timespec='seconds')} "
       r"— DO NOT EDIT BY HAND")
    ap(r"\begin{table}[htbp]")
    ap(r"\centering")
    ap(r"\caption{Campello Brexit Replication Suite}")
    ap(r"\label{tab:h1_5_brexit_did}")
    ap(r"\scriptsize")
    ap(r"\setlength{\tabcolsep}{3pt}")
    ap(r"\begin{tabular}{lcccccccc}")
    ap(r"\toprule")
    ap(r" & \multicolumn{2}{c}{CASH (eq.~14)} "
       r"& \multicolumn{2}{c}{CASH (PSM)} "
       r"& \multicolumn{2}{c}{UncResCEO} "
       r"& \multicolumn{2}{c}{Campello T.8} \\")
    ap(r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}"
       r"\cmidrule(lr){8-9}")
    ap(r" & (1) & (2) & (3) & (4) & (5) & (6) & (7) & (8) \\")
    ap(r" & $\beta^{UK}$ & textual & $\beta^{UK}$ & textual "
       r"& $\beta^{UK}$ & textual & $\beta^{UK}$ & textual \\")
    ap(r" & tercile & Item~1$+$7 & tercile & Item~1$+$7 & tercile "
       r"& Item~1$+$7 & col.~1 & col.~2 \\")
    ap(r"\midrule")

    ap(rf"{LABEL['POST_x_HIGH']} "
       rf"& {delta_cell('cb')} & {delta_cell('c7')} "
       rf"& {delta_cell('pb')} & {delta_cell('p7')} "
       rf"& {delta_cell('ub')} & {delta_cell('u7')} "
       rf"& {_cell(ref_b['cash_delta'], ref_b.get('stars', ''))} "
       rf"& {_cell(ref_t['cash_delta'], ref_t.get('stars', ''))} \\")
    ap(r" & " + " & ".join(f"({M[k]['POST_x_HIGH']['se']:.4f})" for k in KEYS6)
       + rf" & ({ref_b['se']:.4f}) & ({ref_t['se']:.4f}) \\")
    ap(r"\midrule")

    for nm in FIRM_ORDER + ["__LOGA__", "__CONS__"]:
        if nm == "__LOGA__":
            lbl = LABEL["log_assets"]
            E = {k: (M[k].get("log_assets") or M[k].get("log_assets_l1"))
                 for k in KEYS6}
        elif nm == "__CONS__":
            lbl = LABEL["cons_fwd"]
            E = {k: M[k][cons[k]] for k in KEYS6}
        else:
            lbl = LABEL[nm]
            E = {k: M[k][nm] for k in KEYS6}
        ap(rf"{lbl} & "
           + " & ".join(_cell(E[k]["coef"], _stars2(E[k]["pvalue"]))
                        for k in KEYS6)
           + r" & n.r. & n.r. \\")
        ap(r" & " + " & ".join(f"({E[k]['se']:.4f})" for k in KEYS6)
           + r" & & \\")
    ap(r"\midrule")
    ap(r"Firm FE & Yes & Yes & Yes & Yes & Yes & Yes & Yes & Yes \\")
    ap(r"Ind.(FIC100)$\times$qtr FE & Yes & Yes & Yes & Yes & Yes & Yes "
       r"& Yes & Yes \\")
    ap(r"PSM (3-NN, w/ repl.) & No & No & Yes & Yes & No & No & No & No \\")
    ap(r"\midrule")
    ap(r"N & " + " & ".join(f"{R[k]['nobs']:,}" for k in KEYS6)
       + rf" & {ref_b['n']:,} & {ref_t['n']:,} \\")
    ap(r"Firms & " + " & ".join(f"{R[k]['n_firms']:,}" for k in KEYS6)
       + r" & n.r. & n.r. \\")
    ap(r"$R^2$ & "
       + " & ".join(_r2(R[k]["rsquared_within"]) + r"$^{\ddagger}$"
                    for k in KEYS6)
       + rf" & {ref_b['rsquared']:.2f}$^{{\dagger}}$ "
       rf"& {ref_t['rsquared']:.2f}$^{{\dagger}}$ \\")
    ap(r"\bottomrule")
    ap(r"\end{tabular}")
    ap(r"\begin{minipage}{\linewidth}")
    ap(r"\vspace{2pt}\scriptsize")
    ap(r"\textit{Notes:} $^{*}p<.10$, $^{**}p<.05$, $^{***}p<.01$; "
       r"CASH columns (1)--(4) one-tailed, UncResCEO (5)--(6) two-tailed; "
       r"significant coefficients in \textbf{bold}. Standard errors "
       r"(parentheses) double-clustered firm $\times$ calendar-quarter.")
    ap(r"\end{minipage}")
    ap(r"\end{table}")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"sources: {d_bx} | {d_psm} | {d_unc}")
    print(f"written: {OUT}")
    for k, tag in [("cb", "CASH βᵁᴷ"), ("c7", "CASH txt"),
                   ("pb", "PSM βᵁᴷ"), ("p7", "PSM txt"),
                   ("ub", "UncRes βᵁᴷ"), ("u7", "UncRes txt")]:
        c = M[k]["POST_x_HIGH"]
        print(f"  {tag:<11} δ̂ {c['coef']:+.4f} ({c['se']:.4f}) N {R[k]['nobs']:,}")
    print(f"  Campello βᵁᴷ {ref_b['cash_delta']:+.3f}{ref_b.get('stars','')} | "
          f"txt {ref_t['cash_delta']:+.3f}{ref_t.get('stars','')}")


if __name__ == "__main__":
    main()
